// This file is @generated by prost-build.
/// Module defines the ORM module which adds providers to the app container for
/// ORM ModuleDB's and in the future will automatically register query
/// services for modules that use the ORM.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Module {}
